import streamlit as st
import pandas as pd
from pathlib import Path
import os
import re
import subprocess
from dataclasses import dataclass
from datetime import datetime
import html

from authoring.parse import (
    dict_to_manuscript,
    is_segment_divider,
    manuscript_to_dict,
    manuscript_to_markdown,
    parse_chapters_from_markdown,
    split_segments,
)
from authoring.version_store import get_versions_root, list_versions, load_version, save_version
from authoring.export_docx import export_docx
from authoring.export_pdf import export_pdf

# Page configuration
st.set_page_config(
    page_title="The Shadow of Lillya - Novel Completion Project",
    page_icon="📚",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for styling
st.markdown("""
<style>
    .main-header {
        font-size: 3rem;
        font-weight: bold;
        color: #1f77b4;
        text-align: center;
        margin-bottom: 2rem;
    }
    .subtitle {
        font-size: 1.5rem;
        color: #666;
        text-align: center;
        margin-bottom: 3rem;
    }
    .nav-callout {
        border: 1px solid rgba(31, 119, 180, 0.35);
        background: linear-gradient(90deg, rgba(31, 119, 180, 0.12), rgba(142, 68, 173, 0.08));
        padding: 0.9rem 1rem;
        border-radius: 0.75rem;
        margin: 1.25rem 0 1.5rem 0;
    }
    .nav-callout strong {
        color: #1f77b4;
    }
    .section-header {
        font-size: 2rem;
        color: #2c3e50;
        margin-top: 2rem;
        margin-bottom: 1rem;
    }
    .quote {
        font-style: italic;
        color: #7f8c8d;
        text-align: center;
        margin: 2rem 0;
        padding: 1rem;
        background-color: #f8f9fa;
        border-left: 4px solid #1f77b4;
    }
    .reader-wrap {
        max-width: 820px;
        margin: 0 auto;
        line-height: 1.65;
        font-size: 1.06rem;
        color: rgba(20, 20, 20, 0.92);
    }
    .reader-wrap h2 {
        margin-top: 1.4rem;
        margin-bottom: 0.5rem;
    }
    .reader-sep {
        text-align: center;
        color: rgba(44, 62, 80, 0.55);
        margin: 1.25rem 0;
        letter-spacing: 0.2rem;
        user-select: none;
    }

    /* Sidebar styling (Streamlit testid selectors are relatively stable) */
    section[data-testid="stSidebar"] {
        min-width: 320px;
        width: 320px;
        background: linear-gradient(180deg, rgba(31, 119, 180, 0.10), rgba(142, 68, 173, 0.06));
        border-right: 1px solid rgba(44, 62, 80, 0.18);
    }
    section[data-testid="stSidebar"] h2, section[data-testid="stSidebar"] h1, section[data-testid="stSidebar"] h3 {
        letter-spacing: 0.2px;
    }
    section[data-testid="stSidebar"] .sidebar-card {
        border: 1px solid rgba(44, 62, 80, 0.18);
        background: rgba(255, 255, 255, 0.65);
        border-radius: 0.75rem;
        padding: 0.75rem 0.85rem;
        margin-bottom: 0.75rem;
        box-shadow: 0 1px 8px rgba(0,0,0,0.04);
    }
    section[data-testid="stSidebar"] .sidebar-hint {
        font-size: 0.95rem;
        color: rgba(44, 62, 80, 0.82);
        margin-top: 0.25rem;
    }
</style>
""", unsafe_allow_html=True)

MANUSCRIPTS_DIR = Path("manuscripts")

@dataclass(frozen=True)
class DocInfo:
    label: str
    path: Path
    bytes: int
    words: int

@st.cache_data(show_spinner=False)
def _read_text(path: str) -> str:
    p = Path(path)
    return p.read_text(encoding="utf-8", errors="ignore")

def _count_words(text: str) -> int:
    return len(re.findall(r"\b\w+\b", text))

def _discover_markdown_docs() -> list[DocInfo]:
    if not MANUSCRIPTS_DIR.exists():
        return []
    docs: list[DocInfo] = []
    for p in sorted(MANUSCRIPTS_DIR.rglob("*.md")):
        # Avoid showing huge autogenerated artifacts by default; user can still browse files directly.
        if any(part.startswith(".") for part in p.parts):
            continue
        try:
            text = _read_text(str(p))
            size = p.stat().st_size
            docs.append(
                DocInfo(
                    label=str(p.relative_to(MANUSCRIPTS_DIR)),
                    path=p,
                    bytes=size,
                    words=_count_words(text),
                )
            )
        except Exception:
            continue
    return docs

def _script_exists(name: str) -> bool:
    return Path(name).exists()

def _run_python_script(script: str, args: list[str], env: dict[str, str]) -> tuple[int, str, str]:
    cmd = ["python3", script, *args]
    proc = subprocess.run(cmd, capture_output=True, text=True, env=env)
    return proc.returncode, proc.stdout, proc.stderr

def _normalize_openai_key(value: str) -> str:
    v = value.strip().strip('"').strip("'")
    for prefix in ("export ", "OPENAI_API_KEY="):
        if v.startswith(prefix):
            v = v[len(prefix):].strip().strip('"').strip("'")
    m = re.search(r"(sk-(?:proj-)?[A-Za-z0-9_-]{10,})", v)
    return (m.group(1) if m else v).strip()

def _looks_like_openai_key(value: str) -> bool:
    v = _normalize_openai_key(value)
    return v.startswith("sk-") or v.startswith("sk-proj-")

def _looks_like_anthropic_key(value: str) -> bool:
    v = value.strip()
    return v.startswith("sk-ant-")

def _read_shadow_base_markdown() -> tuple[str, str]:
    edited_dir = MANUSCRIPTS_DIR / "Shadow_of_Lillya" / "edited_version"
    candidates = sorted(edited_dir.glob("*.md"))
    if not candidates:
        return "", ""
    preferred = None
    for p in candidates:
        if "Tyson" in p.name or "Rough Draft" in p.name:
            preferred = p
            break
    path = preferred or candidates[0]
    return _read_text(str(path)), str(path)

def _render_segment_html(text: str) -> str:
    # Render plain text as readable paragraphs.
    paragraphs = [p.strip() for p in text.split("\n\n") if p.strip()]
    html_paras = []
    for p in paragraphs:
        html_paras.append(f"<p>{html.escape(p).replace('\\n', '<br/>')}</p>")
    return "\n".join(html_paras)

def _ensure_current_manuscript_in_state() -> None:
    if "current_manuscript" in st.session_state:
        return
    base_md, base_path = _read_shadow_base_markdown()
    if not base_md:
        st.session_state["current_manuscript"] = {"title": "The Shadow of Lillya", "chapters": [], "source_path": None}
        st.session_state["current_version_name"] = "base"
        return
    m = parse_chapters_from_markdown(base_md, manuscript_title="The Shadow of Lillya")
    data = manuscript_to_dict(m)
    data["source_path"] = base_path
    st.session_state["current_manuscript"] = data
    st.session_state["current_version_name"] = "base"

def _split_chapter_text_to_segments(chapter_text: str) -> list[dict]:
    # Accept either *** dividers or plain paragraphs.
    lines = chapter_text.splitlines()
    segs = split_segments(lines)
    if not segs:
        segs = [chapter_text.strip()] if chapter_text.strip() else []
    out = []
    for i, t in enumerate(segs, start=1):
        out.append({"id": f"seg-{i:03d}", "text": t})
    return out

def _move_item(items: list, index: int, delta: int) -> int:
    j = index + delta
    if j < 0 or j >= len(items):
        return index
    items[index], items[j] = items[j], items[index]
    return j

def main():
    # Sidebar navigation (choose page first so we can show a clear "current section" header)
    st.sidebar.markdown(
        """
        <div class="sidebar-card">
          <div style="font-size:1.15rem; font-weight:700; color:#2c3e50;">Navigation</div>
          <div class="sidebar-hint">Pick a section below. The sidebar stays open by default.</div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    nav_items = {
        "🏠 Home": "Home",
        "📚 Manuscripts": "Original Manuscripts",
        "✨ Generate": "Generate Segment",
        "🧪 Attempts": "Segment Attempts",
        "📊 Voice": "Voice Analysis",
        "👤 About": "About Audrey",
    }
    choice = st.sidebar.radio(
        "Go to",
        options=list(nav_items.keys()),
        label_visibility="collapsed",
    )
    page = nav_items[choice]

    # Compact header (always visible) + clear current section indicator
    st.markdown('<h1 class="main-header">The Shadow of Lillya</h1>', unsafe_allow_html=True)
    st.markdown('<p class="subtitle">Novel Completion Project</p>', unsafe_allow_html=True)
    st.markdown(f"**Current section:** {choice}")
    st.markdown("---")

    # Only show the long intro/quote on Home so other pages feel distinct.
    if page == "Home":
        st.markdown('<div class="quote">"The shadow knows what the light cannot see."<br>— Audrey Berger Welz</div>', unsafe_allow_html=True)
        st.markdown("""
        ## About This Project
        
        This space is dedicated to completing **The Shadow of Lillya**, a novel by the late **Audrey Berger Welz**. 
        This work serves as both a sequel and prequel to her previous novel, **Circus of the Queens**.
        
        Our mission is to use multiple Large Language Models to complete the novel as authentically as possible, 
        staying true to Audrey's original intentions and preserving her unique voice and storytelling style.
        """)

        st.markdown(
            """
            <div class="nav-callout">
              <strong>New here?</strong> Use the <strong>left sidebar</strong> to navigate:
              <span style="white-space:nowrap;">📚 Manuscripts</span>,
              <span style="white-space:nowrap;">✨ Generate</span>,
              <span style="white-space:nowrap;">🧪 Attempts</span>,
              <span style="white-space:nowrap;">📊 Voice</span>.
            </div>
            """,
            unsafe_allow_html=True,
        )
    
    if page == "Home":
        show_home_page()
    elif page == "Original Manuscripts":
        show_manuscripts_page()
    elif page == "Generate Segment":
        show_generate_page()
    elif page == "Segment Attempts":
        show_completions_page()
    elif page == "Voice Analysis":
        show_analysis_page()
    elif page == "About Audrey":
        show_about_page()

def show_home_page():
    st.markdown('<h2 class="section-header">Project Overview</h2>', unsafe_allow_html=True)
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown("""
        ### Background
        
        Audrey Berger Welz was a gifted storyteller whose novel *Circus of the Queens* 
        captivated readers with its rich characters and imaginative world-building. 
        *The Shadow of Lillya* represents her vision for expanding this universe, 
        exploring the deeper mysteries and connections within her literary world.
        """)
        
        st.markdown("""
        ### Methodology
        
        We employ multiple approaches to ensure the completion remains faithful to Audrey's vision:
        
        1. **Voice Analysis**: Studying Audrey's writing style, vocabulary, and narrative patterns
        2. **Character Consistency**: Maintaining the depth and complexity of established characters
        3. **Plot Continuity**: Ensuring seamless integration with *Circus of the Queens*
        4. **Multiple LLM Approach**: Using different models to generate and compare completions
        5. **Human Oversight**: Reviewing and selecting the most authentic continuations
        """)
    
    with col2:
        st.markdown("""
        ### Project Structure
        
        This space contains:
        
        - **Original Manuscripts**: Audrey's draft of *The Shadow of Lillya*
        - **Reference Material**: Complete text of *Circus of the Queens* for context
        - **Completion Attempts**: Various LLM-generated continuations
        - **Analysis Tools**: Methods for evaluating authenticity and voice consistency
        """)
        
        st.markdown("""
        ### Current Status
        
        - ✅ Project setup and documentation
        - 📚 Manuscript upload and processing
        - 🔄 LLM completion generation
        - 📊 Voice analysis and comparison
        - 📖 Final manuscript compilation
        """)

def show_manuscripts_page():
    st.markdown('<h2 class="section-header">Original Manuscripts</h2>', unsafe_allow_html=True)

    if not MANUSCRIPTS_DIR.exists():
        st.warning("No `manuscripts/` directory found in the Space repository.")
        return

    docs = _discover_markdown_docs()
    if not docs:
        st.warning("No manuscript markdown files found under `manuscripts/`.")
        return

    st.success(f"Found {len(docs)} manuscript file(s).")

    tabs = st.tabs(["Reader & Versions", "Workflow Tools", "Raw files"])

    with tabs[0]:
        _ensure_current_manuscript_in_state()
        root, persistent_like = get_versions_root()
        st.caption(f"Versions folder: `{root}`" + (" (persistent)" if persistent_like else " (may be ephemeral)"))

        # Version selection
        versions = list_versions()
        version_labels = ["base (Audrey draft)"] + [v.name for v in versions]
        selected_version = st.selectbox("Current version", options=version_labels, index=0)
        if selected_version != st.session_state.get("current_version_name", "base"):
            if selected_version.startswith("base"):
                base_md, base_path = _read_shadow_base_markdown()
                m = parse_chapters_from_markdown(base_md, manuscript_title="The Shadow of Lillya")
                data = manuscript_to_dict(m)
                data["source_path"] = base_path
                st.session_state["current_manuscript"] = data
                st.session_state["current_version_name"] = "base"
            else:
                data = load_version(selected_version)
                st.session_state["current_manuscript"] = data.get("manuscript", data)
                st.session_state["current_version_name"] = selected_version

        manuscript = st.session_state["current_manuscript"]

        col_a, col_b = st.columns([2, 1])
        with col_a:
            new_name = st.text_input("Save as…", placeholder="shadow_042126")
        with col_b:
            if st.button("Save version", use_container_width=True, disabled=not bool(new_name.strip())):
                payload = {
                    "meta": {
                        "created_at": datetime.utcnow().isoformat() + "Z",
                        "based_on": st.session_state.get("current_version_name", "base"),
                    },
                    "manuscript": manuscript,
                }
                save_version(new_name.strip(), payload)
                st.success(f"Saved `{new_name.strip()}`")

        # Exports
        export_col1, export_col2, export_col3 = st.columns(3)
        md_out = manuscript_to_markdown(dict_to_manuscript(manuscript))
        with export_col1:
            st.download_button("Download Markdown", data=md_out, file_name=f"{st.session_state.get('current_version_name','shadow')}.md", mime="text/markdown", use_container_width=True)
        with export_col2:
            try:
                docx_bytes = export_docx(manuscript)
                st.download_button("Download DOCX", data=docx_bytes, file_name=f"{st.session_state.get('current_version_name','shadow')}.docx", mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document", use_container_width=True)
            except Exception as e:
                st.caption(f"DOCX export unavailable: {e}")
        with export_col3:
            try:
                pdf_bytes = export_pdf(manuscript)
                st.download_button("Download PDF", data=pdf_bytes, file_name=f"{st.session_state.get('current_version_name','shadow')}.pdf", mime="application/pdf", use_container_width=True)
            except Exception as e:
                st.caption(f"PDF export unavailable: {e}")

        st.markdown("---")
        chapters = manuscript.get("chapters", [])
        if not chapters:
            st.warning("No chapters parsed yet. Check the edited draft file under `manuscripts/Shadow_of_Lillya/edited_version/`.")
            return

        # Chapter controls
        chap_titles = [c.get("title") or c.get("id") for c in chapters]
        if "reader_chapter_idx" not in st.session_state:
            st.session_state["reader_chapter_idx"] = 0
        chap_idx = st.selectbox("Chapter", options=list(range(len(chapters))), format_func=lambda i: chap_titles[i], index=st.session_state["reader_chapter_idx"])
        st.session_state["reader_chapter_idx"] = chap_idx

        nav1, nav2, nav3, nav4 = st.columns([1, 1, 1, 1])
        with nav1:
            if st.button("↑ Move chapter", disabled=(chap_idx == 0), use_container_width=True):
                st.session_state["reader_chapter_idx"] = _move_item(chapters, chap_idx, -1)
                manuscript["chapters"] = chapters
        with nav2:
            if st.button("↓ Move chapter", disabled=(chap_idx >= len(chapters) - 1), use_container_width=True):
                st.session_state["reader_chapter_idx"] = _move_item(chapters, chap_idx, +1)
                manuscript["chapters"] = chapters
        with nav3:
            if st.button("Add chapter", use_container_width=True):
                chapters.append({"id": f"ch-{len(chapters)+1:03d}", "title": f"New Chapter {len(chapters)+1}", "segments": [{"id": "seg-001", "text": ""}]})
                st.session_state["reader_chapter_idx"] = len(chapters) - 1
                manuscript["chapters"] = chapters
        with nav4:
            if st.button("Delete chapter", use_container_width=True):
                if chapters:
                    chapters.pop(chap_idx)
                    st.session_state["reader_chapter_idx"] = max(0, chap_idx - 1)
                    manuscript["chapters"] = chapters

        chapter = chapters[st.session_state["reader_chapter_idx"]]
        chapter_title = chapter.get("title") or "Chapter"
        chapter["title"] = st.text_input("Chapter title", value=chapter_title)

        segs = chapter.get("segments", [])
        if not segs:
            chapter["segments"] = [{"id": "seg-001", "text": ""}]
            segs = chapter["segments"]

        st.markdown("### Read")
        with st.container():
            st.markdown(f"<div class='reader-wrap'><h2>{html.escape(chapter['title'])}</h2></div>", unsafe_allow_html=True)
            for s in segs:
                st.markdown(f"<div class='reader-wrap'>{_render_segment_html(s.get('text',''))}</div>", unsafe_allow_html=True)
                st.markdown("<div class='reader-sep'>***</div>", unsafe_allow_html=True)

        st.markdown("---")
        st.markdown("### Edit")
        seg_labels = [f"{i+1}. {s.get('id','segment')}" for i, s in enumerate(segs)]
        if "reader_seg_idx" not in st.session_state:
            st.session_state["reader_seg_idx"] = 0
        seg_idx = st.selectbox("Segment", options=list(range(len(segs))), format_func=lambda i: seg_labels[i], index=st.session_state["reader_seg_idx"])
        st.session_state["reader_seg_idx"] = seg_idx
        seg = segs[seg_idx]
        seg["text"] = st.text_area("Segment text", value=seg.get("text", ""), height=260)
        edit1, edit2, edit3 = st.columns(3)
        with edit1:
            if st.button("Add segment", use_container_width=True):
                segs.append({"id": f"seg-{len(segs)+1:03d}", "text": ""})
                st.session_state["reader_seg_idx"] = len(segs) - 1
        with edit2:
            if st.button("↑ Move segment", disabled=(seg_idx == 0), use_container_width=True):
                st.session_state["reader_seg_idx"] = _move_item(segs, seg_idx, -1)
        with edit3:
            if st.button("↓ Move segment", disabled=(seg_idx >= len(segs) - 1), use_container_width=True):
                st.session_state["reader_seg_idx"] = _move_item(segs, seg_idx, +1)

        chapter["segments"] = segs
        manuscript["chapters"][st.session_state["reader_chapter_idx"]] = chapter
        st.session_state["current_manuscript"] = manuscript

    with tabs[1]:
        # Project workflow status
        st.markdown("### Audrey-first workflow status")
        col_a, col_b, col_c = st.columns(3)
        with col_a:
            st.write("**Extracted original material**")
            st.code("manuscripts/Shadow_of_Lillya/audrey_original/audrey_original_compiled.md", language=None)
            st.write("✅" if Path("manuscripts/Shadow_of_Lillya/audrey_original/audrey_original_compiled.md").exists() else "— not generated yet")
        with col_b:
            st.write("**Edited for clarity**")
            st.code("manuscripts/Shadow_of_Lillya/audrey_edited/audrey_edited_clean.md", language=None)
            st.write("✅" if Path("manuscripts/Shadow_of_Lillya/audrey_edited/audrey_edited_clean.md").exists() else "— not generated yet")
        with col_c:
            st.write("**Final compilation**")
            st.code("manuscripts/Shadow_of_Lillya/final_compilation/shadow_of_lillya_final.md", language=None)
            st.write("✅" if Path("manuscripts/Shadow_of_Lillya/final_compilation/shadow_of_lillya_final.md").exists() else "— not generated yet")

        st.markdown("### Run workflow tools (optional)")
        tool_env = os.environ.copy()
        col1, col2, col3 = st.columns(3)
        with col1:
            if st.button("1) Extract Audrey original", use_container_width=True, disabled=not _script_exists("extract_audrey_material.py")):
                with st.spinner("Running extract_audrey_material.py..."):
                    rc, out, err = _run_python_script("extract_audrey_material.py", [], tool_env)
                (st.success if rc == 0 else st.error)(f"Exit code: {rc}")
                if out:
                    st.text_area("stdout", out, height=220)
                if err:
                    st.text_area("stderr", err, height=220)
        with col2:
            if st.button("2) Edit for clarity", use_container_width=True, disabled=not _script_exists("edit_audrey_material.py")):
                with st.spinner("Running edit_audrey_material.py..."):
                    rc, out, err = _run_python_script("edit_audrey_material.py", [], tool_env)
                (st.success if rc == 0 else st.error)(f"Exit code: {rc}")
                if out:
                    st.text_area("stdout", out, height=220)
                if err:
                    st.text_area("stderr", err, height=220)
        with col3:
            if st.button("3) Compile final manuscript", use_container_width=True, disabled=not _script_exists("compile_final_manuscript.py")):
                with st.spinner("Running compile_final_manuscript.py..."):
                    rc, out, err = _run_python_script("compile_final_manuscript.py", [], tool_env)
                (st.success if rc == 0 else st.error)(f"Exit code: {rc}")
                if out:
                    st.text_area("stdout", out, height=220)
                if err:
                    st.text_area("stderr", err, height=220)

    with tabs[2]:
        st.markdown("### Browse manuscripts (raw)")
        doc_by_label = {d.label: d for d in docs}
        selected = st.selectbox("Select a document", options=list(doc_by_label.keys()), key="raw_doc_select")
        info = doc_by_label[selected]
        st.caption(f"`{info.path}` • {info.words:,} words • {info.bytes/1024/1024:.2f} MB")

        max_chars = st.slider("Preview length (characters)", min_value=2_000, max_value=80_000, value=10_000, step=2_000, key="raw_preview_len")
        text = _read_text(str(info.path))
        preview = text[:max_chars]
        st.text_area("Preview", preview, height=420, key="raw_preview")
        st.download_button("Download full document", data=text, file_name=info.path.name, mime="text/markdown", key="raw_download")

        st.markdown("---")
        st.markdown("### Search across manuscripts")
        q = st.text_input("Keyword / phrase", placeholder="e.g., Lillya, circus, queen, shadow, chapter, character name…", key="raw_search_q")
        context = st.slider("Context characters around match", 40, 400, 120, 20, key="raw_search_ctx")
        max_hits = st.slider("Max hits to show", 5, 50, 15, 5, key="raw_search_hits")

        if q.strip():
            q_norm = q.strip()
            hits = []
            for d in docs:
                t = _read_text(str(d.path))
                for m in re.finditer(re.escape(q_norm), t, flags=re.IGNORECASE):
                    start = max(0, m.start() - context)
                    end = min(len(t), m.end() + context)
                    snippet = t[start:end].replace("\n", " ")
                    hits.append((d.label, snippet))
                    if len(hits) >= max_hits:
                        break
                if len(hits) >= max_hits:
                    break

            if not hits:
                st.info("No matches found.")
            else:
                st.success(f"Showing {len(hits)} match(es).")
                for i, (label, snippet) in enumerate(hits, 1):
                    st.markdown(f"**{i}.** `{label}`")
                    st.code(snippet, language=None)

def show_generate_page():
    st.markdown('<h2 class="section-header">Generate Segment</h2>', unsafe_allow_html=True)
    
    st.markdown("""
    Generate a new segment of *The Shadow of Lillya* using LLM technology.
    The system will use Audrey's manuscripts as context to maintain her voice and style.
    """)
    
    col1, col2 = st.columns(2)
    
    with col1:
        provider = "openai"
        model_name = "gpt-4"
        st.markdown(f"**LLM:** OpenAI (`{model_name}`)")
        max_tokens = st.slider("Max Tokens", 500, 4000, 2000)
        use_audrey_first = st.checkbox("Prefer Audrey-first edited material (if available)", value=True)
    
    with col2:
        writing_request = st.text_area(
            "Writing request (optional)",
            placeholder="Example: Write a chapter about Lillya going to the Coronation of Czar Nicholas.",
            height=120,
        )
        target_words = st.slider("Target words (guideline)", 300, 4000, 1400, 100)
    
    if st.button("Generate Segment", type="primary"):
        with st.spinner("Generating segment..."):
            try:
                import sys
                
                # Context is auto-managed (kept out of the UI to avoid confusion).
                # Build command
                cmd = [sys.executable, "llm_completion.py", 
                       "--model", provider,
                       "--model-name", model_name,
                       "--max-tokens", str(max_tokens),
                       "--target-words", str(target_words)]

                if use_audrey_first:
                    cmd.append("--use-audrey-first")
                
                if writing_request.strip():
                    cmd.extend(["--writing-request", writing_request.strip()])
                
                # Set environment variables
                env = os.environ.copy()
                
                result = subprocess.run(cmd, capture_output=True, text=True, env=env)
                
                if result.returncode == 0:
                    st.success("✅ Segment generated successfully!")
                    st.text_area("Output", result.stdout, height=260)
                else:
                    st.error("❌ Error generating segment")
                    if result.stdout:
                        st.text_area("stdout", result.stdout, height=200)
                    if result.stderr:
                        st.text_area("stderr", result.stderr, height=240)
            except Exception as e:
                st.error(f"❌ Error: {e}")
    
    st.markdown("---")
    st.markdown("### Recent Segments")
    
    # List recent segments (stored under completion_attempts/ for compatibility)
    completion_dir = Path("completion_attempts")
    if completion_dir.exists():
        completion_files = list(completion_dir.rglob("*.md"))
        completion_files.sort(key=lambda x: x.stat().st_mtime, reverse=True)
        
        if completion_files:
            for comp_file in completion_files[:5]:
                with st.expander(f"📄 {comp_file.name}"):
                    with open(comp_file, 'r', encoding='utf-8') as f:
                        content = f.read()
                    st.markdown(content[:1000] + "..." if len(content) > 1000 else content)
        else:
            st.info("No segments generated yet. Use the form above to generate your first segment.")

def show_completions_page():
    st.markdown('<h2 class="section-header">Segment Attempts</h2>', unsafe_allow_html=True)
    
    # List all segments (stored under completion_attempts/ for compatibility)
    completion_dir = Path("completion_attempts")
    if completion_dir.exists():
        completion_files = list(completion_dir.rglob("*.md"))
        completion_files.sort(key=lambda x: x.stat().st_mtime, reverse=True)
        
        if completion_files:
            st.success(f"Found {len(completion_files)} segment(s)")
            
            # Group by model
            by_model = {}
            for comp_file in completion_files:
                model = comp_file.parent.name
                if model not in by_model:
                    by_model[model] = []
                by_model[model].append(comp_file)
            
            for model, files in by_model.items():
                with st.expander(f"📚 {model.replace('_', ' ').title()} ({len(files)} files)"):
                    for comp_file in files:
                        st.markdown(f"**{comp_file.name}**")
                        with open(comp_file, 'r', encoding='utf-8') as f:
                            content = f.read()
                        st.text_area("Preview", content[:500] + "..." if len(content) > 500 else content, 
                                   key=str(comp_file), height=200)
        else:
            st.info("🔄 No segments found. Go to 'Generate Segment' to create your first segment.")
    else:
        st.info("🔄 LLM segments will be generated and displayed here.")

def show_analysis_page():
    st.markdown('<h2 class="section-header">Voice Analysis</h2>', unsafe_allow_html=True)
    
    st.info("📊 Voice analysis tools and comparisons will be available here.")
    
    # Placeholder for analysis tools
    st.markdown("""
    ### Analysis Tools
    
    This section will provide tools for:
    
    - **Style Comparison** - Analyzing Audrey's writing patterns
    - **Vocabulary Analysis** - Word choice and frequency analysis
    - **Character Voice Consistency** - Ensuring character authenticity
    - **Plot Coherence** - Story structure and flow analysis
    """)

def show_about_page():
    st.markdown('<h2 class="section-header">About Audrey Berger Welz</h2>', unsafe_allow_html=True)
    
    st.markdown("""
    ### Remembering Audrey
    
    Audrey Berger Welz was a talented author whose creative vision brought *Circus of the Queens* 
    to life. Her storytelling captured the imagination of readers with its unique blend of 
    fantasy, mystery, and human emotion.
    
    *The Shadow of Lillya* represents her final creative project, a continuation of the 
    world she so beautifully crafted. This project honors her memory by bringing her 
    vision to completion.
    
    ### Acknowledgments
    
    We remember and honor **Audrey Berger Welz** for her creative vision and the beautiful 
    worlds she created. This project is a labor of love dedicated to bringing her final 
    story to completion.
    """)
    
    st.markdown("""
    ### Contact
    
    This is a deeply personal project honoring Audrey's literary legacy. While this space 
    serves as a memorial and completion effort, we welcome respectful engagement with the material.
    """)

if __name__ == "__main__":
    main()



