#!/usr/bin/env python3
"""
LLM Completion Workflow for The Shadow of Lillya
Supports multiple LLMs for generating novel completions
"""

import os
import json
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Optional
import argparse

class LLMCompletion:
    """Base class for LLM completion"""
    
    def __init__(self, model_name: str):
        self.model_name = model_name
        self.completions_dir = Path("completion_attempts")
        self.completions_dir.mkdir(exist_ok=True)
    
    def load_manuscripts(self) -> Dict[str, str]:
        """Load all manuscript files"""
        manuscripts = {}
        manuscripts_dir = Path("manuscripts")

        # Prefer Audrey-first edited material if it exists (generated by edit_audrey_material.py)
        audrey_first_path = Path("manuscripts/Shadow_of_Lillya/audrey_edited/audrey_edited_clean.md")
        if audrey_first_path.exists():
            with open(audrey_first_path, "r", encoding="utf-8") as f:
                manuscripts["shadow_edited"] = f.read()
        
        # Load Circus of the Queens
        circus_dir = manuscripts_dir / "Circus_of_the_Queens"
        for md_file in circus_dir.glob("*.md"):
            with open(md_file, 'r', encoding='utf-8') as f:
                manuscripts['circus_of_the_queens'] = f.read()
        
        # Load edited version of Shadow of Lillya (fallback if Audrey-first not present)
        if "shadow_edited" not in manuscripts:
            edited_dir = manuscripts_dir / "Shadow_of_Lillya" / "edited_version"
            for md_file in edited_dir.glob("*.md"):
                with open(md_file, 'r', encoding='utf-8') as f:
                    manuscripts['shadow_edited'] = f.read()
        
        # Load unedited material
        unedited_dir = manuscripts_dir / "Shadow_of_Lillya" / "unedited_material"
        unedited_texts = []
        for md_file in unedited_dir.glob("*.md"):
            with open(md_file, 'r', encoding='utf-8') as f:
                unedited_texts.append(f.read())
        manuscripts['shadow_unedited'] = '\n\n---\n\n'.join(unedited_texts)
        
        # Load notes and outlines
        shadow_dir = manuscripts_dir / "Shadow_of_Lillya"
        notes = []
        for md_file in shadow_dir.glob("*.md"):
            if 'notes' in md_file.name.lower() or 'outline' in md_file.name.lower():
                with open(md_file, 'r', encoding='utf-8') as f:
                    notes.append(f.read())
        manuscripts['notes'] = '\n\n---\n\n'.join(notes)
        
        return manuscripts
    
    def create_prompt(
        self,
        manuscripts: Dict[str, str],
        continuation_point: Optional[str] = None,
        *,
        circus_chars: int = 4000,
        shadow_tail_chars: int = 12000,
        unedited_chars: int = 2000,
        notes_chars: int = 4000,
        target_words: int = 1400,
    ) -> str:
        """Create a prompt for LLM completion"""
        circus = manuscripts.get("circus_of_the_queens", "")
        shadow = manuscripts.get("shadow_edited", "")
        unedited = manuscripts.get("shadow_unedited", "")
        notes = manuscripts.get("notes", "")

        circus_excerpt = circus[: max(0, circus_chars)]
        shadow_excerpt = shadow[-max(0, shadow_tail_chars) :] if shadow_tail_chars > 0 else ""
        unedited_excerpt = unedited[: max(0, unedited_chars)]
        notes_excerpt = notes[: max(0, notes_chars)]

        prompt = f"""You are completing the novel "The Shadow of Lillya" by Audrey Berger Welz. This is a sequel/prequel to her novel "Circus of the Queens."

CONTEXT - CIRCUS OF THE QUEENS:
{circus_excerpt}

CURRENT MANUSCRIPT - THE SHADOW OF LILLYA (Edited Version):
{shadow_excerpt}

ADDITIONAL MATERIAL - UNEDITED VERSIONS:
{unedited_excerpt}

NOTES AND OUTLINES:
{notes_excerpt}

INSTRUCTIONS:
1. Continue the story from where Audrey left off, maintaining her unique voice and writing style
2. Stay true to the characters and world established in "Circus of the Queens"
3. Preserve the thematic elements and narrative style of Audrey's work
4. Ensure character consistency and plot coherence
5. Write in a style that matches Audrey's voice as closely as possible

CONTINUATION POINT:
{continuation_point if continuation_point else 'Continue from the end of the edited manuscript.'}

OUTPUT:
- Write approximately {target_words} words (flexible).
- Keep continuity with the final paragraphs of the Shadow excerpt above.
- Do not include analysis or meta commentary—just the next section of the novel text.
"""
        
        return prompt
    
    def generate_completion(self, prompt: str, max_tokens: int = 2000) -> str:
        """Generate completion using the LLM (to be implemented by subclasses)"""
        raise NotImplementedError("Subclasses must implement generate_completion")
    
    def save_completion(self, completion: str, metadata: Dict) -> Path:
        """Save completion to file"""
        model_dir = self.completions_dir / self.model_name.lower().replace(' ', '_')
        model_dir.mkdir(exist_ok=True)
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"completion_{timestamp}.md"
        filepath = model_dir / filename
        
        # Create markdown file with metadata
        content = f"""# Completion Attempt - {self.model_name}

**Generated:** {metadata.get('timestamp', datetime.now().isoformat())}
**Model:** {self.model_name}
**Version:** {metadata.get('version', '1.0')}
**Continuation Point:** {metadata.get('continuation_point', 'End of edited manuscript')}

---

## Generated Continuation

{completion}

---

## Metadata

```json
{json.dumps(metadata, indent=2)}
```
"""
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        # Also save metadata separately
        metadata_file = model_dir / f"metadata_{timestamp}.json"
        with open(metadata_file, 'w', encoding='utf-8') as f:
            json.dump(metadata, f, indent=2)
        
        return filepath

class OpenAICompletion(LLMCompletion):
    """OpenAI GPT completion"""
    
    def __init__(self, model_name: str = "gpt-4", api_key: Optional[str] = None):
        super().__init__(f"OpenAI-{model_name}")
        self.model_name_full = model_name
        self.api_key = api_key or os.getenv('OPENAI_API_KEY')
        if not self.api_key:
            raise ValueError("OpenAI API key required. Set OPENAI_API_KEY environment variable.")
        if self.api_key.strip().startswith("OPENAI_") or "OPENAI_API_KEY" in self.api_key or self.api_key.strip().startswith("OPENAI_API_KEY="):
            raise ValueError(
                "OpenAI API key looks invalid (it appears you provided the env var name, not the key). "
                "Set OPENAI_API_KEY to your actual key that starts with 'sk-'."
            )
    
    def generate_completion(self, prompt: str, max_tokens: int = 2000) -> str:
        """Generate completion using OpenAI API"""
        try:
            from openai import OpenAI
            client = OpenAI(api_key=self.api_key)
            
            response = client.chat.completions.create(
                model=self.model_name_full,
                messages=[
                    {"role": "system", "content": "You are a literary assistant helping to complete a novel in the author's voice and style."},
                    {"role": "user", "content": prompt}
                ],
                max_tokens=max_tokens,
                temperature=0.7
            )
            
            return response.choices[0].message.content
        except ImportError:
            raise ImportError("OpenAI library not installed. Run: pip install openai")
        except Exception as e:
            raise Exception(f"OpenAI API error: {e}")

class AnthropicCompletion(LLMCompletion):
    """Anthropic Claude completion"""
    
    def __init__(self, model_name: str = "claude-3-opus-20240229", api_key: Optional[str] = None):
        super().__init__(f"Anthropic-{model_name}")
        self.model_name_full = model_name
        self.api_key = api_key or os.getenv('ANTHROPIC_API_KEY')
        if not self.api_key:
            raise ValueError("Anthropic API key required. Set ANTHROPIC_API_KEY environment variable.")
    
    def generate_completion(self, prompt: str, max_tokens: int = 2000) -> str:
        """Generate completion using Anthropic API"""
        try:
            from anthropic import Anthropic
            client = Anthropic(api_key=self.api_key)
            
            response = client.messages.create(
                model=self.model_name_full,
                max_tokens=max_tokens,
                messages=[
                    {"role": "user", "content": prompt}
                ]
            )
            
            return response.content[0].text
        except ImportError:
            raise ImportError("Anthropic library not installed. Run: pip install anthropic")
        except Exception as e:
            raise Exception(f"Anthropic API error: {e}")

def main():
    parser = argparse.ArgumentParser(description='Generate LLM completions for The Shadow of Lillya')
    parser.add_argument('--model', choices=['openai', 'anthropic'], default='openai',
                       help='LLM provider to use')
    parser.add_argument('--model-name', type=str,
                       help='Specific model name (e.g., gpt-4, claude-3-opus-20240229)')
    parser.add_argument('--api-key', type=str,
                       help='API key (or set environment variable)')
    parser.add_argument('--max-tokens', type=int, default=2000,
                       help='Maximum tokens to generate')
    parser.add_argument('--continuation-point', type=str,
                       help='Specific point in text to continue from')
    parser.add_argument('--use-audrey-first', action='store_true',
                        help='Prefer Audrey-first edited material if present (default behavior). Included for clarity in logs/UI.')
    parser.add_argument('--circus-chars', type=int, default=4000,
                        help='How many characters of Circus to include (from the beginning)')
    parser.add_argument('--shadow-tail-chars', type=int, default=12000,
                        help='How many characters of Shadow to include (from the end)')
    parser.add_argument('--unedited-chars', type=int, default=2000,
                        help='How many characters of unedited Shadow material to include')
    parser.add_argument('--notes-chars', type=int, default=4000,
                        help='How many characters of notes/outlines to include')
    parser.add_argument('--target-words', type=int, default=1400,
                        help='Approximate word target for the continuation')
    
    args = parser.parse_args()
    
    # Load manuscripts
    print("📚 Loading manuscripts...")
    base_completion = LLMCompletion("base")
    manuscripts = base_completion.load_manuscripts()
    print(f"  ✓ Loaded {len(manuscripts)} manuscript sections")
    
    # Create prompt
    print("📝 Creating prompt...")
    prompt = base_completion.create_prompt(
        manuscripts,
        args.continuation_point,
        circus_chars=args.circus_chars,
        shadow_tail_chars=args.shadow_tail_chars,
        unedited_chars=args.unedited_chars,
        notes_chars=args.notes_chars,
        target_words=args.target_words,
    )
    print(f"  ✓ Prompt created ({len(prompt)} characters)")
    
    # Initialize LLM
    print(f"🤖 Initializing {args.model}...")
    if args.model == 'openai':
        model_name = args.model_name or "gpt-4"
        llm = OpenAICompletion(model_name, args.api_key)
    elif args.model == 'anthropic':
        model_name = args.model_name or "claude-3-opus-20240229"
        llm = AnthropicCompletion(model_name, args.api_key)
    
    # Generate completion
    print("✨ Generating completion...")
    try:
        completion = llm.generate_completion(prompt, args.max_tokens)
        print(f"  ✓ Generated {len(completion)} characters")
        
        # Save completion
        metadata = {
            'model': llm.model_name,
            'model_full': model_name,
            'timestamp': datetime.now().isoformat(),
            'continuation_point': args.continuation_point or 'End of edited manuscript',
            'max_tokens': args.max_tokens,
            'completion_length': len(completion)
        }
        
        filepath = llm.save_completion(completion, metadata)
        print(f"  ✓ Saved to: {filepath}")
        
    except Exception as e:
        print(f"  ✗ Error: {e}")
        return 1
    
    return 0

if __name__ == '__main__':
    exit(main())
